Repository dgraph-io/dgraph-docs, pull requests merged in 2024-07, with the labels that each got.

#617 Update _index.md to clarify cloud security on by default
  content/graphql/security/_index.md
Labels: Stale

#657 docs(dql): Updated schema alter from date, to datetime
  content/dql/dql-get-started.md
Labels: Stale

#630 [Docs] Dgraph CLI Reference
  content/deploy/cli-command-reference.md
Labels: Stale

#269 Corrrect of defining a Type in GraphQL Response
  content/graphql/lambda/overview.md
Labels: investigate, triage:delayed, Stale

#426 chore(diagram): add diagram code
  diagrams/GraphQL_Logo.png
  diagrams/apollo.png
  diagrams/curl.png
  diagrams/dgraph.png
  diagrams/dgraph.py
  diagrams/dgraphlg.png
  diagrams/dgraphlgEC2.png
  diagrams/grpc.png
  diagrams/http.png
  diagrams/readme.md
Labels: Stale

#382 docs(graphql): Update id directive for interfaces (#209)
  content/graphql/schema/directives/ids.md
Labels: cherry-pick, Stale
